# example values

indexing-settings:
  sites:
#    - url: https://www.lenta.ru   #индексируется без ошибок
#      name: Лента.ру
    - url: https://www.skillbox.ru  #индексируется без ошибок
      name: Skillbox
#    - url: http://www.playback.ru   #индексируется без ошибок
#      name: PlayBack.Ru
#    - url: https://volochek.life/   #индексируется без ошибок
#      name: Volochek
#    - url: https://radiomv.ru/   #Ошибка при загрузке: https://www.radiomv.ru/ | PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
#      name: RadioMV
#    - url: https://ipfran.ru/  # индексируется без ошибок
#      name: IPFRAN
#    - url: https://dimonvideo.ru/   #Ошибка при загрузке: https://www.dimonvideo.ru/ | No subject alternative DNS name matching www.dimonvideo.ru found.
#      name: DimonVideo
#    - url: https://nikoartgallery.com/  #Forbidden Access denied.
#      name: NikoArtGallery
#    - url: https://et-cetera.ru/mobile/  # пока не индексируется
#      name: ET-CETERA
#    - url: https://www.lutherancathedral.ru/  #индексируется без ошибок
#      name: Lutheran_Cathedral
#    - url: https://dombulgakova.ru/  #индексируется без ошибок
#      name: DomBulgakova
#    - url: https://www.svetlovka.ru/  # индексируется без ошибок
#      name: Svetlovka
server:
  port: 8080

spring:
  datasource:
    username: postgres
    password:
    url: jdbc:postgresql://localhost:5432/search_engine
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml